#+TITLE: Curriculum Vitae
#+DATE: [2022-06-25 sáb]

* Description :noexport:

This file is used to generate my curriculum vitae built with Emacs + Org-mode +
LaTeX. I decided to use Org-Mode and Latex because I'm striving to learn more
about Emacs, ELisp and its ecosystem, and LaTeX is a very complete system to
create beautiful documents, so this is a natural path to follow.

Some tags to keep in mind when reading this configuration:

- The ~:noexport:~ tag allows trees and/or sub-trees to not be exported into the
  pdf. I tag all of my configuration subtrees with this tag and all of the
  content that I do not want to export for a particular job.
- The ~:ignore:~ tag allows the contents of a tree or sub-tree to be exported
  without exporting the heading. This is useful for giving the document a good
  structure so that it is easy to work and understand it.

** References

+ [[https://www.aidanscannell.com/post/org-mode-resume/][Creating a CV/Resume in Org-Mode using LaTeX Templates]]
+ [[https://github.com/aidanscannell/my-org-resume][Github repository from the previous article]]

* Config/Preamble :noexport:

** LaTeX Config

#+BEGIN_SRC emacs-lisp :exports none :results none :eval always
  ; C-c C-c
  (setq org-latex-logfiles-extensions
        (quote
         ("lof" "lot" "tex~" "aux" "idx" "log" "out" "toc" "nav" "snm" "vrb"
          "dvi" "fdb_latexmk" "blg" "brf" "fls" "entoc" "ps" "spl" "bbl" "xmpi"
          "run.xml" "bcf")))
  (add-to-list 'org-latex-classes
               '("altacv" "\\documentclass[10pt,a4paper,ragged2e,withhyper]{altacv}

  % Change the page layout if you need to
  \\geometry{left=1.25cm,right=1.25cm,top=1.5cm,bottom=1.5cm,columnsep=1.2cm}

  % Use roboto and lato for fonts
  \\renewcommand{\\familydefault}{\\sfdefault}

  % Change the colours if you want to
  \\definecolor{SlateGrey}{HTML}{2E2E2E}
  \\definecolor{LightGrey}{HTML}{666666}
  \\definecolor{DarkPastelRed}{HTML}{450808}
  \\definecolor{PastelRed}{HTML}{8F0D0D}
  \\definecolor{GoldenEarth}{HTML}{E7D192}
  \\colorlet{name}{black}
  \\colorlet{tagline}{PastelRed}
  \\colorlet{heading}{DarkPastelRed}
  \\colorlet{headingrule}{GoldenEarth}
  \\colorlet{subheading}{PastelRed}
  \\colorlet{accent}{PastelRed}
  \\colorlet{emphasis}{SlateGrey}
  \\colorlet{body}{LightGrey}

  % Change some fonts, if necessary
  \\renewcommand{\\namefont}{\\Huge\\rmfamily\\bfseries}
  \\renewcommand{\\personalinfofont}{\\footnotesize}
  \\renewcommand{\\cvsectionfont}{\\LARGE\\rmfamily\\bfseries}
  \\renewcommand{\\cvsubsectionfont}{\\large\\bfseries}

  % Change the bullets for itemize and rating marker
  % for \cvskill if you want to
  \\renewcommand{\\itemmarker}{{\\small\\textbullet}}
  \\renewcommand{\\ratingmarker}{\\faCircle}
  "

                 ("\\cvsection{%s}" . "\\cvsection*{%s}")))
  (setq org-latex-packages-alist 'nil)
  (setq org-latex-default-packages-alist
        '(("rm" "roboto"  t)
          ("defaultsans" "lato" t)
          ("" "paracol" t)
          ))
#+END_SRC

#+LATEX_CLASS: altacv
#+LATEX_HEADER: \columnratio{0.6} % Set the left/right column width ratio to 6:4.
#+LATEX_HEADER: \usepackage[bottom]{footmisc}

*** Bibliography

# #+LATEX_HEADER: \DeclareNameAlias{sortname}{last-first}
#+LATEX_HEADER: \DeclareNameAlias{sortname}{given-family}
#+LATEX_HEADER: \addbibresource{my-bib.bib}
# #+LATEX_HEADER: \usepackage[citestyle=numeric-comp, maxcitenames=1, maxbibnames=4, doi=false, isbn=false, eprint=true, backend=bibtex, hyperref=true, url=false, natbib=true]{biblatex}
# #+LATEX_HEADER: \usepackage[backend=biber, sorting=nyvt, style=authoryear, firstinits]{biblatex}
# #+LATEX_HEADER: \usepackage[backend=natbib, giveninits=true]{biblatex}
#+LATEX_HEADER: \usepackage[style=trad-abbrv,sorting=none,sortcites=true,doi=false,url=false,giveninits=true,hyperref]{biblatex}

** Exporter Settings

#+AUTHOR: Vinícius Gajo Marques Oliveira
#+EXPORT_FILE_NAME: ./gajo-cv.pdf
#+OPTIONS: toc:nil title:nil H:1
#+LATEX_HEADER: \columnratio{0.6} % Set the left/right column width ratio to 6:4.

** Macros

#+BEGIN_QUOTE
  AltaCV LaTeX template defines four macros that I wanted to use. These are for
  formatting the ~cvevent~, ~cvachievement~, ~cvtag~ and ~divider~ (horizontal
  dashed line). I convert the LaTeX macros to org-mode macros by adding the
  following lines:
#+END_QUOTE

#+MACRO: cvevent \cvevent{$1}{$2}{$3}{$4}
#+MACRO: cvachievement \cvachievement{$1}{$2}{$3}{$4}
#+MACRO: cvtag \cvtag{$1}
#+MACRO: cvskill \cvskill{$1}{$2}
#+MACRO: divider \divider
#+MACRO: par-div \par\divider
#+MACRO: new-page \newpage

* CV Header :ignore:

** Photo & Tagline :ignore:

#+begin_export latex
\name{Vinícius Gajo M. Oliveira}
\photoR{2.8cm}{me.png}
\tagline{Mechatronics Engineer | Software \& Infrastructure Engineer}
#+end_export

** Personal Info :ignore:

#+begin_export latex
\personalinfo{
  \homepage{https://gaio.dev}
  \email{vinigaio97@gmail.com}
  \location{Minas Gerais, BR}
  \github{64J0}
  \linkedin{vinicius-gajo}
}
\makecvheader
#+end_export

* CV Column 1 :ignore:

#+begin_export latex
\begin{paracol}{2}
#+end_export

** Personal Statement Developer :ignore:

#+begin_export latex
\begin{quote}
``Mechatronics Engineer with great passion for technology. Full-stack Web Developer with DevOps and Infrastructure skills focused in Microsoft Azure.''  
\end{quote}
#+end_export

** Personal Statement Mechatronics Engineer :ignore:noexport:

#+begin_export latex
\begin{quote}
``I am a Mechatronics Engineer with experience in different fields of engineering, like: Structural Mechanics, Networking system and Computer systems development.''  
\end{quote}
#+end_export

** Experience
*** Datarisk :ignore:
{{{cvevent(Software Engineer II - DevSecOps leader, Datarisk, Mar 2022 --
Ongoing, Home-Office)}}}

Leading a small team focused on development operations and infrastructure,
applying DevSecOps and SRE principles.

{{{cvtag(Azure)}}}
{{{cvtag(Terraform)}}}
{{{cvtag(Git, Gitlab and GitHub)}}}
{{{cvtag(F\# (.NET))}}}
{{{cvtag(Linux)}}}
{{{cvtag(Kubernetes)}}}
{{{cvtag(Docker)}}}
{{{cvtag(DevOps)}}}

{{{par-div}}}
{{{cvevent(Software Engineer I, Datarisk, Jul 2021 -- Mar 2022, Home-Office)}}}

Full-stack Web Developer working in a consultancy project for a big brazilian
company dealing with F#, PostgreSQL and Docker in order to serve machine
learning (ML) models.

{{{cvtag(Full-stack web development)}}}
{{{cvtag(F\# (.NET))}}}
{{{cvtag(React.js)}}}
{{{cvtag(Fable \& Feliz)}}}
{{{cvtag(SQL)}}}
{{{cvtag(Docker)}}}
{{{cvtag(PostgreSQL)}}}

*** JMV Technology :ignore:

{{{par-div}}}
{{{cvevent(Full-stack Web Developer, JMV Technology, Feb 2021 -- Jul 2021,
Divinopolis-MG)}}}

Working in a team building a new multimedia platform from scratch using Vue.js,
Node.js with Express and TypeScript. I was also doing some research about ffmpeg
tool.

{{{cvtag(TypeScript)}}}
{{{cvtag(SASS/SCSS)}}}
{{{cvtag(Full-stack)}}}
{{{cvtag(Vue.js)}}}
{{{cvtag(Back-end)}}}
{{{cvtag(Node.js)}}}

{{{par-div}}}
{{{cvevent(Front-end Web Developer, JMV Technology, Nov 2020 -- Feb 2021,
Divinopolis-MG)}}}

Working in a multimedia streaming company. Initially I was involved only in
Front-end JavaScript projects, giving maintenance to systems created with
Angular JS and React (class components).

{{{cvtag(JavaScript)}}}
{{{cvtag(Front-end)}}}
{{{cvtag(React.js)}}}
{{{cvtag(Angular JS)}}}

** Newpage :ignore:

{{{new-page}}}

** Experience (Cont.) :ignore:

*** Master Internet :ignore:

{{{par-div}}}
{{{cvevent(NOC Analyst, Master Internet, May 2020 -- Nov 2020,
Divinopolis-MG)}}}

- Monitoring of network infrastructure assets to guarantee the SLA.
- Analysis of the company's backbone, ensuring the operability of gateways,
  switches and routers.
- Wireless, FTTH and FC equipment analysis.
- Service and support for B2B customers.

{{{cvtag(Computer Networks)}}}
{{{cvtag(Support)}}}

*** Full Engenharia :ignore:

{{{par-div}}}
{{{cvevent(Mechanical Engineering Intern and Jr. Web Developer, Full Engenharia,
Oct 2019 -- Oct 2020, Divinopolis-MG)}}}

During this time I worked initially with mechanical design, creating 3D models
using Autodesk Inventor, running structural static simulations with Ansys
Workbench and creating 2D draws using AutoCAD.

Later I started working in the development of a platform to manage company's
projects, consisting of a Rest API on the back-end developed with JavaScript
(Node.js and Express), and using MongoDB as the main database. In the front-end
I decided to use React.js.

{{{cvtag(AutoCAD)}}}
{{{cvtag(Autodesk Inventor)}}}
{{{cvtag(Ansys Workbench)}}}
{{{cvtag(HTML 5)}}}
{{{cvtag(CSS 3)}}}
{{{cvtag(JavaScript)}}}
{{{cvtag(React.js)}}}
{{{cvtag(Node.js)}}}

** Projects

*** Monitor :ignore:

{{{par-div}}}
{{{cvevent(Student monitor, CEFET-MG, Mar 2019 - Oct 2019, Divinopolis-MG)}}}

In order to help students to understand some topics there are some monitor
students. I was the monitor for two disciplines: Hydraulics & Pneumatics (theory
and lab), and Metrology (theory and lab).

{{{cvtag(Hydraulic systems)}}}
{{{cvtag(Pneumatic systems)}}}
{{{cvtag(Metrology)}}}

*** Quebramato BAJA :ignore:

{{{par-div}}}
{{{cvevent(Quebramato BAJA, CEFET-MG, 2016 - 2018, Divinopolis-MG)}}}

BAJA is a competition regulated by SAE (Society of Automotive Engineers) where
teams compete by creating a single-seater off-road vehicle. In CEFET-MG, Campus
V, we have the Quebramato BAJA team. There I worked in the following
tasks/sub-systems:

- Design of braking systems.
- Electronics system.

{{{cvtag(Braking systems)}}}
{{{cvtag(Electronics)}}}
{{{cvtag(Auto Engineering)}}}

** A day of my life :noexport:
** Publications :noexport:
** Volunteering :noexport:
* CV Column 2 :ignore:

#+begin_export latex
\switchcolumn
#+end_export
  
** Skills

{{{cvtag(Microsoft Azure)}}}
{{{cvtag(Terraform)}}}
{{{cvtag(Docker)}}}
{{{cvtag(Kubernetes)}}}
{{{cvtag(Gitlab)}}}
{{{cvtag(F\# (.NET))}}}
{{{cvtag(PostgreSQL)}}}
{{{cvtag(Linux)}}}
{{{cvtag(Functional programming)}}}

{{{divider}}}

{{{cvtag(HTML5)}}}
{{{cvtag(CSS3)}}}
{{{cvtag(JavaScript)}}}
{{{cvtag(TypeScript)}}}
{{{cvtag(JavaScript)}}}
{{{cvtag(Git/GitHub)}}}
{{{cvtag(Full-stack web dev)}}}
{{{cvtag(React.js)}}}
{{{cvtag(Node.js)}}}

{{{divider}}}

{{{cvtag(Emacs)}}}
{{{cvtag(DevOps/DevSecOps)}}}
{{{cvtag(SRE)}}}
{{{cvtag(Cloud computing)}}}
{{{cvtag(Python)}}}

# {{{divider}}}

# {{{cvtag(AutoCAD)}}}
# {{{cvtag(Autodesk Inventor)}}}
# {{{cvtag(Ansys Workbench)}}}

# {{{divider}}}

# {{{cvtag(Excel)}}}
# {{{cvtag(Word)}}}

** Education

{{{cvevent(Bachelor's degree in Mechatronics Engineering, CEFET-MG, 2015 -
2021)}}}

** Certificates

{{{cvachievement(\faCertificate, Microsoft AZ-900, Foundational knowledge of
cloud services and how those services are provided with Microsoft Azure.)}}}

{{{divider}}}

{{{cvachievement(\faCertificate, Microsoft DP-900, Knowledge of code data
concepts and related Microsoft Azure data services.)}}}

{{{divider}}}

{{{cvachievement(\faCertificate, Microsoft AI-900, Foundational knowledge of
machine learning (ML) and artificial intelligence (AI) concepts and related
Microsoft Azure services.)}}}

{{{divider}}}

{{{cvachievement(\faCertificate, Microsoft SC-900, Fundamental knowledge in
security, compliance and identity in Azure and Microsoft 365.)}}}

{{{divider}}}

{{{cvachievement(\faCertificate, Coursera, Machine Learning Specialization)}}}

{{{divider}}}

{{{cvachievement(\faTrophy, JavaScript (Intermediate), HackerRank)}}}

{{{divider}}}

{{{cvachievement(\faTrophy, SQL (Intermediate), HackerRank)}}}

{{{divider}}}

{{{cvachievement(\faTrophy, Bootcamp GoStack 11, Rocketseat)}}}

{{{divider}}}

{{{cvachievement(\faTrophy, Bootcamp de Formação SRE, ElvenWorks)}}}

# {{{divider}}}

# {{{cvachievement(\faTrophy, Practical Ethical Hacking, TCM Security)}}}

** My Life Philosophy :noexport:
** Achievements :noexport:
** Languages

{{{cvskill(Portuguese, 5)}}}

{{{cvskill(English, 4)}}}

** Referees :noexport:
* Backmatter :ignore:

#+begin_export latex
\end{paracol}
\end{document}
#+end_export

