#+TITLE: Curriculum Vitae
#+DATE: [2022-06-25 sáb]

* Description :noexport:

This file is used to generate my curriculum vitae built with Emacs + Org-mode +
LaTeX. I decided to use Org-Mode and Latex because I'm striving to learn more
about Emacs, ELisp and its ecosystem, so this is a natural path to follow.

Some tags to keep in mind when reading this configuration:

- The ~:noexport:~ tag allows trees and/or sub-trees to not be exported into the
  pdf.
- The ~:ignore:~ tag allows the contents of a tree or sub-tree to be exported
  without exporting the heading.

** References

+ [[https://www.aidanscannell.com/post/org-mode-resume/][Creating a CV/Resume in Org-Mode using LaTeX Templates]]
+ [[https://github.com/aidanscannell/my-org-resume][Github repository from the previous article]]

* Config/Preamble :noexport:

** LaTeX Config

#+BEGIN_SRC emacs-lisp :exports none :results none :eval always
  ; C-c C-c
  (setq org-latex-logfiles-extensions
        (quote
         ("lof" "lot" "tex~" "aux" "idx" "log" "out" "toc" "nav" "snm" "vrb"
          "dvi" "fdb_latexmk" "blg" "brf" "fls" "entoc" "ps" "spl" "bbl" "xmpi"
          "run.xml" "bcf")))
  (add-to-list 'org-latex-classes
               '("altacv" "\\documentclass[10pt,a4paper,ragged2e,withhyper]{altacv}

  % Change the page layout if you need to
  \\geometry{left=1.25cm,right=1.25cm,top=1.5cm,bottom=1.5cm,columnsep=1.2cm}

  % Use roboto and lato for fonts
  \\renewcommand{\\familydefault}{\\sfdefault}

  % Change the colours if you want to
  \\definecolor{SlateGrey}{HTML}{2E2E2E}
  \\definecolor{LightGrey}{HTML}{666666}
  \\definecolor{DarkPastelRed}{HTML}{450808}
  \\definecolor{PastelRed}{HTML}{8F0D0D}
  \\definecolor{GoldenEarth}{HTML}{E7D192}
  \\colorlet{name}{black}
  \\colorlet{tagline}{PastelRed}
  \\colorlet{heading}{DarkPastelRed}
  \\colorlet{headingrule}{GoldenEarth}
  \\colorlet{subheading}{PastelRed}
  \\colorlet{accent}{PastelRed}
  \\colorlet{emphasis}{SlateGrey}
  \\colorlet{body}{LightGrey}

  % Change some fonts, if necessary
  \\renewcommand{\\namefont}{\\Huge\\rmfamily\\bfseries}
  \\renewcommand{\\personalinfofont}{\\footnotesize}
  \\renewcommand{\\cvsectionfont}{\\LARGE\\rmfamily\\bfseries}
  \\renewcommand{\\cvsubsectionfont}{\\large\\bfseries}

  % Change the bullets for itemize and rating marker
  % for \cvskill if you want to
  \\renewcommand{\\itemmarker}{{\\small\\textbullet}}
  \\renewcommand{\\ratingmarker}{\\faCircle}
  "

                 ("\\cvsection{%s}" . "\\cvsection*{%s}")))
  (setq org-latex-packages-alist 'nil)
  (setq org-latex-default-packages-alist
        '(("rm" "roboto"  t)
          ("defaultsans" "lato" t)
          ("" "paracol" t)
          ))
#+END_SRC

#+LATEX_CLASS: altacv
#+LATEX_HEADER: \columnratio{0.6} % Set the left/right column width ratio to 6:4.
#+LATEX_HEADER: \usepackage[bottom]{footmisc}

*** Bibliography

# #+LATEX_HEADER: \DeclareNameAlias{sortname}{last-first}
#+LATEX_HEADER: \DeclareNameAlias{sortname}{given-family}
#+LATEX_HEADER: \addbibresource{my-bib.bib}
# #+LATEX_HEADER: \usepackage[citestyle=numeric-comp, maxcitenames=1, maxbibnames=4, doi=false, isbn=false, eprint=true, backend=bibtex, hyperref=true, url=false, natbib=true]{biblatex}
# #+LATEX_HEADER: \usepackage[backend=biber, sorting=nyvt, style=authoryear, firstinits]{biblatex}
# #+LATEX_HEADER: \usepackage[backend=natbib, giveninits=true]{biblatex}
#+LATEX_HEADER: \usepackage[style=trad-abbrv,sorting=none,sortcites=true,doi=false,url=false,giveninits=true,hyperref]{biblatex}

** Exporter Settings

#+AUTHOR: Vinícius Gajo Marques Oliveira
#+EXPORT_FILE_NAME: ./gajo-cv.pdf
#+OPTIONS: toc:nil title:nil H:1
#+LATEX_HEADER: \columnratio{0.6} % Set the left/right column width ratio to 6:4.

** Macros

#+BEGIN_QUOTE
  AltaCV LaTeX template defines four macros that I wanted to use. These are for
  formatting the ~cvevent~, ~cvachievement~, ~cvtag~ and ~divider~ (horizontal
  dashed line). I convert the LaTeX macros to org-mode macros by adding the
  following lines:
#+END_QUOTE

#+MACRO: cvevent \cvevent{$1}{$2}{$3}{$4}
#+MACRO: cvachievement \cvachievement{$1}{$2}{$3}{$4}
#+MACRO: cvtag \cvtag{$1}
#+MACRO: divider \divider
#+MACRO: par-div \par\divider
#+MACRO: new-page \newpage

* CV Header :ignore:

** Photo & Tagline :ignore:

#+begin_export latex
\name{Vinícius Gajo Marques Oliveira}
\photoR{2.8cm}{me.png}
\tagline{Mechatronics Engineer | Full-stack Software Engineer | DevOps}
#+end_export

** Personal Info :ignore:

#+begin_export latex
\personalinfo{
  \homepage{https://gaio.dev}
  \email{vinigaio97@gmail.com}
  \phone{+55 37 99929-1330}
  \location{Minas Gerais, BR}
  \github{64J0}
  \linkedin{vinicius-gajo}
}
\makecvheader
#+end_export

* CV Column One :ignore:

#+begin_export latex
\begin{paracol}{2}
#+end_export
  
** Experience
*** Software Engineer II :ignore:
*** Software Engineer I :ignore:
*** Full-stack Web Developer :ignore:
*** Front-end Web Developer Jr :ignore:
*** Network Operations Center Analyst :ignore:
*** Mechanical Engineering Intern :ignore:
** Projects
** A day of my life :noexport:
** Publications :noexport:
** Volunteering
* CV Column Two :ignore:

#+begin_export latex
\switchcolumn
#+end_export
  
** Skills
** Education
** My Life Philosophy :noexport:
** Achievements
** Languages :noexport:
** Referees
* Backmatter :ignore:

#+begin_export latex
\end{paracol}
\end{document}
#+end_export

